import { Content } from "./types";

export const defaultContent: Content = {
  settings: {
    name: "Sai Vaibhav",
    role: "Cinematographer",
    tagline: "Cinematographer — Commercials & Brand Films",
    location: "Bengaluru, India",
    bio: "I'm selective about what I take on now. I'd rather work on fewer projects that challenge me and demand a certain level of craft. If you have something that needs that kind of attention, I'm always open to building it.",
    heroVideoId: "2M3c8id9_oI",
    profilePhotoUrl:
      "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1000&auto=format&fit=crop",
    aboutHeading: "Crafting visual narratives with intention.",
    phone: "",
    whatsapp: "919880945952",
    email: "saivaibhav49@gmail.com",
    bookingUrl: "https://calendar.app.google/CWUjCsUy39m5ghiQ6",
    socials: {
      instagram: "#",
      youtube: "#",
      linkedin: "#",
    },
  },
  hero: {
    images: [
      "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=2622&auto=format&fit=crop",
    ],
    intervalMs: 6000,
  },
  projects: [
    {
      id: "1",
      title: "Ford TIC Launch Event",
      videoUrl: "https://youtu.be/L4Cs1JafgY4",
      videoId: "L4Cs1JafgY4",
      platform: "youtube",
      category: "Corporate Event + Architecture",
      tags: ["Events"],
      priority: 1,
    },
    {
      id: "2",
      title: "Ola MoveOS2 Launch",
      videoUrl: "https://youtu.be/iVQxxEQVH-E",
      videoId: "iVQxxEQVH-E",
      platform: "youtube",
      category: "Event Aftermovie / Product Ad",
      tags: ["Events", "Brand Films"],
      priority: 2,
    },
    {
      id: "3",
      title: "FIL Bangalore Aftermovie",
      videoUrl: "https://youtu.be/fQGhOKNUhls",
      videoId: "fQGhOKNUhls",
      platform: "youtube",
      category: "Event Aftermovie",
      tags: ["Events"],
      priority: 2,
    },
    {
      id: "4",
      title: "The Estates Club Inauguration",
      videoUrl: "https://youtu.be/y41W82NXqYc",
      videoId: "y41W82NXqYc",
      platform: "youtube",
      category: "Event Aftermovie",
      tags: ["Events"],
      priority: 3,
    },
    {
      id: "5",
      title: "GrowthSchool Party Aftermovie",
      videoUrl: "https://youtu.be/WXDwRjA1Im4",
      videoId: "WXDwRjA1Im4",
      platform: "youtube",
      category: "Event Aftermovie",
      tags: ["Events"],
      priority: 3,
    },
    {
      id: "6",
      title: "YogiFi Product Ad",
      videoUrl: "https://youtu.be/zavY5Lx36o4",
      videoId: "zavY5Lx36o4",
      platform: "youtube",
      category: "Product Ad",
      tags: ["Brand Films"],
      priority: 1,
    },
    {
      id: "7",
      title: "Futurense Leadership Council Film",
      videoUrl: "https://youtu.be/2M3c8id9_oI",
      videoId: "2M3c8id9_oI",
      platform: "youtube",
      category: "Brand Film",
      tags: ["Brand Films"],
      priority: 1,
    },
    {
      id: "8",
      title: "Wolves by UpGrad",
      videoUrl: "https://youtu.be/bgTRGqeFkHk",
      videoId: "bgTRGqeFkHk",
      platform: "youtube",
      category: "Brand Film",
      tags: ["Brand Films"],
      priority: 2,
    },
    {
      id: "9",
      title: "Palo Alto GPTW",
      videoUrl: "https://youtu.be/ff6PgH2U8N8",
      videoId: "ff6PgH2U8N8",
      platform: "youtube",
      category: "Brand Film",
      tags: ["Brand Films"],
      priority: 1,
    },
    {
      id: "10",
      title: "Scaler Brand Film",
      videoUrl: "https://youtu.be/9tjVxmUJkWU",
      videoId: "9tjVxmUJkWU",
      platform: "youtube",
      category: "Brand Film",
      tags: ["Brand Films"],
      priority: 2,
    },
    {
      id: "11",
      title: "Care Clean Documentary",
      videoUrl: "https://youtu.be/DQMv4CObusc",
      videoId: "DQMv4CObusc",
      platform: "youtube",
      category: "Corporate Documentary",
      tags: ["Documentary"],
      priority: 1,
    },
    {
      id: "12",
      title: "Arihant Group of Institutions",
      videoUrl: "https://youtu.be/gzbe-qFFmOE",
      videoId: "gzbe-qFFmOE",
      platform: "youtube",
      category: "Presenter Style Ads",
      tags: ["Brand Films"],
      priority: 3,
    },
    {
      id: "15",
      title: "Network School",
      videoUrl: "https://www.instagram.com/reel/DTZ23yAEdO2/?igsh=MWJsZjlhY2VvZnp4MQ==",
      videoId: "DTZ23yAEdO2",
      platform: "instagram",
      category: "Instagram",
      tags: ["Instagram"],
      priority: 1,
    },
    {
      id: "16",
      title: "EIMR",
      videoUrl: "https://drive.google.com/file/d/1P4X8zmtd_utPyeQsZrjoMVf4YZYqaXPB/view",
      videoId: "1P4X8zmtd_utPyeQsZrjoMVf4YZYqaXPB",
      platform: "drive",
      category: "Instagram",
      tags: ["Instagram"],
      priority: 2,
    },
  ],
  testimonials: [
    {
      id: "t1",
      name: "Marlon",
      role: "Founder",
      quote: "Working with Sai was completely stress-free from start to finish. He understood the brief instantly, communicated clearly throughout, and handled everything seamlessly without needing constant input. His reliability and professionalism made the entire process effortless.",
      order: 0,
    },
    {
      id: "t2",
      name: "Dheemaan",
      role: "Photographer/Videographer",
      quote: "Sai is one of the most reliable creatives I've worked with\u2014punctual, precise, and easy to collaborate with. He brings in creative shots while staying aligned with the brief, and consistently delivers exactly what's needed with strong communication throughout.",
      order: 1,
    },
  ],
  filters: ["Featured", "Events", "Brand Films", "Documentary", "Instagram", "All"],
};
